### ISSUE TITLE
Use consistent version numbers

### ISSUE THREAD

**Issue by diesl** [IGreatlyDislikeJavascript/bootstrap-tourist#27]
First of all, thanks for collecting all bugfixes and new features to keep Bootstrap Tour alive 👍 

But I think in order to make this project even better, you should be consistent with version numbers. I took a look around and got a bit confused by a few things. Maybe you can fix some of them:

- At [npm](https://www.npmjs.com/package/bootstrap-tourist/v/0.2.1), there is a version **0.2.1** but I can not find it here
- At the [releases page](https://github.com/IGreatlyDislikeJavascript/bootstrap-tourist/releases):
  - The latest version is tagged **v0.2.0**
  - The version before is tagged **0.2.0**, but code and description reveal it is **0.12**
  - The first version is tagged **v0.10-beta**

The versioning seems problematic to me, because **0.2** is smaller than **0.12**. I see you speak of a labelling change in the changelog, but still...
This can be problematic for systems like npm that rely on consistentversioning scheme with ascending version numbers. Checking again, I see the first version is labelled as **0.0.10** over there. I can easily imagine why ;)

Take a look at [semver.org](https://semver.org/). In my opinion, this is the best way to deal with version numbers.

Another minor issue: [In the code](https://github.com/IGreatlyDislikeJavascript/bootstrap-tourist/commit/82bff6d4d32c701e623a90b73ee05660e1213577#diff-8d92f5e0d2fcc75c260e1de82ca9983c), you write "_Entirely based upon boostrap-tour v.0.2.0_". But the newest bootstrap tour version I could find is 0.12

**Comment by IGreatlyDislikeJavascript** [comment]
The short answer. 

- npm v0.2.1 is the latest, stable release
- current github repo version should be stable and considered to be candidate for v0.2.2

Either are fine to use. Npm is indeed 1 minor version ahead of github release!

-----
The long answer:

There are times when all I can do is nod, hang my head in shame, and completely agree that I utterly failed to do this correctly :-).

In my defense, Tourist was only ever meant to be a collection of quick fixes to Tour - I never intended to take on ownership of this, but it just kind of happened. As I've said in a few places, I'm not a js coder or web developer (I'm an old C / x86 asm coder from the 90s), I'd never really used github, and I inherited the need for Tourist for various reasons and thought I'd share my efforts in the slim chance they'd be useful. Nobody was more surprised (and extremely happy!) than me when people started using and contributing!

So, excuses aside, you're absolutely correct. The current versioning mismatch is partially because of this pull request: ( https://github.com/IGreatlyDislikeJavascript/bootstrap-tourist/pull/22 ). I wanted to push the update to npm so that lukaszmn could move his project to npm and use his own pull, and didn't update github release at the same time. Yes, I know, hit me with the idiot stick for not updating everything else.

The situation as of **30th August** is:

- The npm version is correctly labelled 0.2.1. It contains the major fixes of 0.2.0, plus lukaszmn's pull for delayOnElement enhancements. This is **the latest stable release**.

- The latest **release** on github is 0.2.0. This is also stable, but doesn't contain lukaszmn's pull. Therefore 0.2.0 is the correct version number.

- The current code in the github repo is nominally the candidate for 0.2.2, which is stable and has a few minor updates (and will shortly have thenewbeat addStep enhancements added too).

- The unstable/new_backdrop branch is a continuation of the collaboration with ibastevan and his pull ( https://github.com/IGreatlyDislikeJavascript/bootstrap-tourist/pull/24 ). This is a major change to how the backdrop is managed. It's branched from 0.2.2 candidate.

- The next formal release on npm / github will be 0.3. Ideally this will be with the new backdrop implemented, once we're happy it's working.


> Another minor issue: In the code, you write "Entirely based upon boostrap-tour v.0.2.0". But the newest bootstrap tour version I could find is 0.12

Now I get to point fingers ;-) . Original Tour v0.11 and v0.12 were used interchangeably, so their versioning is wrong too... I'm just going to delete that version bit!

**Comment by diesl** [comment]
> There are times when all I can do is nod, hang my head in shame, and completely agree that I utterly failed to do this correctly :-).

I will forgive you now that I see you really regret ;)

> I never intended to take on ownership of this, but it just kind of happened

Haha, I know that. Must be fate ;)

Thanks also for the detailed explanation of the current situation. I would suggest to

- release the 0.2.1 version with lukaszmn's pull also here on github
- change the 0.2.0 tag to the correct 0.12 tag at the second release if that's possible

The new release plan looks fine to me.

**Comment by IGreatlyDislikeJavascript** [comment]
v0.3.0 is now the master branch, and will be a release. I won't push it to npm as it's a major change and want to let it bed in some more first.

**Comment by diesl** [comment]
> I won't push it to npm as it's a major change and want to let it bed in some more first.

But you already released it here on Github. What's the difference? I you release it, it should be released everywhere.

If you are unsure about stability I suggest to tag the version as _beta_.

By the way, `bootstrap-tourist.js` has the wrong version number in its top comment.

**Comment by tszulc** [comment]
We have started on the process to get the package on the same version, and following semantic versioning. Read more here: IGreatlyDislikeJavascript/bootstrap-tourist#16
