### ISSUE TITLE
Can you put this on npm?

### ISSUE THREAD

**Issue by gsrafael01** [IGreatlyDislikeJavascript/bootstrap-tourist#3]
Would be nice to have this on [npm](https://www.npmjs.com/).

**Comment by IGreatlyDislikeJavascript** [comment]
Stupid question - does it have to be *me* that puts it onto npm, or could someone else (such as yourself for example) do that?

Just to reiterate a couple of points about Tourist - I'm not a javascript coder, I only had a need to fix the original Tour for a project. I then decided to help by adding features/fixes and starting the move to ES6 as per discussion in the original Tour repo. Also, Tourist is a work in progress: a constant debug build or beta version, until it's complete enough to be given back to sorich87 and the original Tour team if they want it.

Anyone using Tourist should be very aware that it may contain bugs (as per the readme), so I'm kinda OK with forcing people to laboriously download the repo and implement Tourist manually, as it reinforces the beta nature of it - hence this repo only containing 3 files instead of a more normal "distro" with build, tests etc.

That said, I'm more than happy for anyone to take Tourist and put it into npm or anything else that "makes things better", with the only proviso that it doesn't make fixing bugs, adding features and moving to ES6 any "harder".

**Comment by gsrafael01** [comment]
I doesn't have to be you, but since you're the developer, you would be able to always keep the package up to date.

There's nothing wrong with putting it as a beta version on npm (your README is also shown there), and it shouldn't affect your development at all. All you need to do is create your account on npm, install Node.js, and run these commands from the terminal in your working directory:

```
npm init
npm login
npm publish
```

Then every time you want to update the package, simply run `npm publish` again.

**Comment by IGreatlyDislikeJavascript** [comment]
Okay, so I think I've done this using the package name "bootstrap-tourist". Would appreciate you checking this?

Please be warned, I have never done this before so I don't know if it's packaged and published correctly. I strongly recommend just using the repo download option here on github!

**Comment by gsrafael01** [comment]
It's perfect, thanks!

I just prefer to automate every task I can for my projects, saves a lot of time.
