### ISSUE TITLE
Make bootstrap-tourist available as a webjar

### ISSUE THREAD

**Issue by surli** [IGreatlyDislikeJavascript/bootstrap-tourist#5]
We currently use bootstrap-tour in our project, included as a [webjar](https://www.webjars.org/). In order to migrate towards tourist, we would need it to be available as webjar. 
It's not possible currently to deploy it as one since contrary to bootstrap-tour it doesn't contain a package.json to build it as an NPM package. 

Would that be possible to add one to the repo?

**Comment by IGreatlyDislikeJavascript** [comment]
Hi, as you'll find out if you dig into the docs, I'm not a JS coder! So unfortunately you'll have to help me out here.

The purpose of Tourist and this repo is to be a beta and in-development version to add fixes and features, and migrate to native ES6. That's why there's no minified version, package.json etc

I looked at the link and it seems complex, or at least some understanding and work is needed to create a webjar. So if you can point me to a simple explanation I can consider doing a webjar if it's not complex or time consuming to maintain. Alternatively please feel free to do it yourself and publish it.

Tourist is available on NPM already though, does that help? See here: https://github.com/IGreatlyDislikeJavascript/bootstrap-tourist/issues/3

**Comment by surli** [comment]
> Tourist is available on NPM already though, does that help? See here: #3

Thanks for the hint. So I deployed it using that info with the automated UI of webjars and it's now available on Maven etc, see: https://search.maven.org/artifact/org.webjars.npm/bootstrap-tourist/0.0.10/jar

**Comment by PhantomYdn** [comment]
Hello!
It's strange, but it seems that webjars see only old version of the lib - max is 0.2.1, but according to github it should be 0.3 already in NPM. Please advice how to get the recent version.

And thank you for your work!

**Comment by IGreatlyDislikeJavascript** [comment]
@PhantomYdn you're welcome, glad you find Tourist useful.

The latest version of Tourist is marked as a release here on Github - please use that one for the moment. Please also take note of the changelog and the significant update to backdrop in v0.3.x

As for npm, semantic versioning and all the stuff that makes life easy: the issue is my complete failure and lack of knowledge :-) . Please see this thread: [tszulc is solving my problems](https://github.com/IGreatlyDislikeJavascript/bootstrap-tourist/issues/16#issuecomment-550027001)

I'm heading off on vacation so it's going to be a couple of weeks before I get everything back in line, sorry.
