### ISSUE TITLE
Angular

### ISSUE THREAD

**Issue by scriptsure** [IGreatlyDislikeJavascript/bootstrap-tourist#53]
We have an angularjs application using angular material... If we just included bootstrap css and bootstrap-tourist would we be able to get it codebase to work? Has anyone tried this???

**Comment by IGreatlyDislikeJavascript** [comment]
Hi, thanks for your question. The short answer is no, you must include bootstrap as a whole to use Tourist.

The longer answer: Tourist is a drop-in replacement fork of Bootstrap Tour that fixes many issues and adds requested features. I continued Tourist because the original developers of Tour were no longer maintaining it.

Original tour had a stand alone version that didn't rely on bootstrap. However the way the developers achieved this was by extracting and duplicating large amounts of Bootstrap core code. So, in reality, the reliance on bootstrap remained, it was just a hacked solution to providing it. I didn't have the time or need to maintain that approach. If you wanted to try something similar you'll need to extract all the popover and tooltip code from bootstrap. Alternatively, you could directly use popper.js.

**Comment by scriptsure** [comment]
@IGreatlyDislikeJavascript yeah thanks a lot... awesome work here.... wow. I totally agree on other project what a mess. I actually don't think it is a major deal to include the bootstrap and angular material css. The size of bootstrap is like 25kb so no really pressure there... I don't think that there will be any issues with disrupting current css... I hope.

But in terms of injecting and using with angular no issues??? I will give it a try...

**Comment by scriptsure** [comment]
@IGreatlyDislikeJavascript do you happen to know what module I inject into angularjs for tourist? And what references in controllers for service?

**Comment by IGreatlyDislikeJavascript** [comment]
@scriptsure I'm really sorry but I don't know how to answer your question. I'm not a .js coder, this bit of readme will explain more and set expectations:
https://github.com/IGreatlyDislikeJavascript/bootstrap-tourist/blob/master/README.md#policy-on-npm-semantic-versioning-releases-code-structure-etc

If you get it working, I'm sure others would appreciate a guide and I'd be happy to include implementation steps in the docs.
